#!/usr/bin/env python3
"""
Generate tab4_baselines.tex from phase4_baselines.json
for the IIWA14 combined scene baseline comparison.

Usage:
    python3 gen_tab4_baselines.py [input.json] [output.tex]
"""

import json
import math
import os
import sys

import numpy as np


def gen_tab4_baselines(data):
    """Generate LaTeX table from Phase 4 baseline comparison data."""

    sbf = data["sbf"]
    iris = data.get("iris_gcs", {})
    rrt_data = data.get("rrt_connect", {})
    prm_data = data.get("prm", {})

    def aggregate_sampling(planner_data):
        """Aggregate per-query × per-seed results."""
        times = []
        lengths = []
        n_total = 0
        n_succ = 0
        for qname, runs in planner_data.items():
            for r in runs:
                n_total += 1
                if r.get("success"):
                    n_succ += 1
                    times.append(r["time_s"])
                    lengths.append(r["path_length"])
        sr = 100.0 * n_succ / n_total if n_total else 0
        return {
            "sr": sr,
            "time_median": float(np.median(times)) if times else None,
            "time_mean": float(np.mean(times)) if times else None,
            "time_std": float(np.std(times)) if times else None,
            "length_median": float(np.median(lengths)) if lengths else None,
            "length_mean": float(np.mean(lengths)) if lengths else None,
        }

    rrt_agg = aggregate_sampling(rrt_data)
    prm_agg = aggregate_sampling(prm_data)

    # IRIS-NP + GCS
    iris_precomp = iris.get("iris_time_total_s", 0)
    n_regions = iris.get("n_regions", 0)
    gcs_queries = iris.get("queries", {})
    gcs_times = []
    gcs_lengths = []
    gcs_n = 0
    gcs_ok = 0
    for qname, r in gcs_queries.items():
        gcs_n += 1
        if r.get("success"):
            gcs_ok += 1
            gcs_times.append(r["time_s"])
            if r.get("path_length") is not None:
                gcs_lengths.append(r["path_length"])
    gcs_sr = 100.0 * gcs_ok / gcs_n if gcs_n else 0
    gcs_q_med = float(np.median(gcs_times)) if gcs_times else None
    gcs_l_med = float(np.median(gcs_lengths)) if gcs_lengths else None

    # Build table
    lines = [
        r"% Auto-generated by gen_tab4_baselines.py from phase4_baselines.json",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{End-to-end comparison on the IIWA14 combined scene "
        r"(shelves + bins + table, 16 obstacles, 5 query pairs).}",
        r"\label{tab:baselines}",
        r"\small",
        r"\begin{tabular}{@{}lrrrr@{}}",
        r"\toprule",
        r"Planner & Precomp.\,(s) & Query\,(s) & Cost\,(rad) & SR\,(\%) \\",
        r"\midrule",
    ]

    # SBF row
    sbf_build = sbf.get("build_median", 0)
    sbf_query = sbf.get("query_median", 0)
    sbf_len = sbf.get("path_length") or sbf.get("len_median", 0)
    sbf_sr = sbf.get("sr", 0)
    lines.append(
        f"  \\textbf{{SBF (ours)}} & {sbf_build:.2f} "
        f"& {sbf_query:.3f} "
        f"& {sbf_len:.3f} & {sbf_sr:.0f} \\\\"
    )

    lines.append(r"  \midrule")

    # IRIS-NP + GCS row
    gcs_q_str = f"{gcs_q_med:.3f}" if gcs_q_med is not None else "---"
    gcs_l_str = f"{gcs_l_med:.3f}" if gcs_l_med is not None else "---"
    lines.append(
        f"  IRIS-NP + GCS ({n_regions} reg.) & {iris_precomp:.1f} "
        f"& {gcs_q_str} "
        f"& {gcs_l_str} & {gcs_sr:.0f} \\\\"
    )

    # RRT-Connect row
    rrt_t_str = f"{rrt_agg['time_median']:.3f}" if rrt_agg["time_median"] is not None else "---"
    rrt_l_str = f"{rrt_agg['length_median']:.3f}" if rrt_agg["length_median"] is not None else "---"
    lines.append(
        f"  RRT-Connect & --- "
        f"& {rrt_t_str} "
        f"& {rrt_l_str} & {rrt_agg['sr']:.0f} \\\\"
    )

    # PRM row
    prm_build = data.get("summary", {}).get("prm_build_median_s", None)
    prm_t_str = f"{prm_agg['time_median']:.3f}" if prm_agg["time_median"] is not None else "---"
    prm_l_str = f"{prm_agg['length_median']:.3f}" if prm_agg["length_median"] is not None else "---"
    prm_pre_str = f"{prm_build:.1f}" if prm_build is not None else "---"
    lines.append(
        f"  PRM (3000 nodes) & {prm_pre_str} "
        f"& {prm_t_str} "
        f"& {prm_l_str} & {prm_agg['sr']:.0f} \\\\"
    )

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]

    return "\n".join(lines)


def main():
    input_json = sys.argv[1] if len(sys.argv) > 1 else \
        os.path.join(os.path.dirname(__file__), "..",
                     "experiments", "results_new", "phase4_baselines.json")
    output_tex = sys.argv[2] if len(sys.argv) > 2 else \
        os.path.join(os.path.dirname(__file__), "..",
                     "paper", "generated", "tab4_baselines.tex")

    if not os.path.exists(input_json):
        print(f"ERROR: {input_json} not found. Run run_baselines.py first.")
        sys.exit(1)

    with open(input_json) as f:
        data = json.load(f)

    tex = gen_tab4_baselines(data)

    os.makedirs(os.path.dirname(output_tex), exist_ok=True)
    with open(output_tex, "w") as f:
        f.write(tex + "\n")

    print(f"Written {output_tex}")
    print(tex)


if __name__ == "__main__":
    main()
