#!/usr/bin/env python3
"""Regenerate canonical paper tables (tab_build, tab_ablation) and
canonical_numbers.csv from the 10-seed/16-thread JSON outputs of
exp6_build_timing and exp5_ablation.

Master statistical protocol: 10 seeds, median + IQR(P25-P75), 16 threads,
cold ~/.sbf_cache. Sources of truth:

  cpp/v6/experiments/results_new/exp6_10seed_16thr.json
  cpp/v6/experiments/results_new/exp5_10seed_16thr.json

Outputs:

  cpp/v6/doc/generated/tab_build.tex       (\input by both EN and ZH)
  cpp/v6/doc/generated/tab_ablation.tex
  cpp/v6/doc/generated/canonical_numbers.csv

Usage:
  python3 cpp/v6/scripts/regen_paper_tables.py
"""

from __future__ import annotations

import csv
import json
from pathlib import Path
from statistics import median

import numpy as np

REPO = Path(__file__).resolve().parents[2]
RES = REPO / "v6" / "experiments" / "results_new"
GEN = REPO / "v6" / "doc" / "generated"
GEN.mkdir(parents=True, exist_ok=True)

EXP6 = RES / "exp6_10seed_16thr.json"
EXP5 = RES / "exp5_10seed_16thr.json"


def iqr(values: list[float]) -> tuple[float, float, float]:
    """Return (median, q25, q75) using linear interpolation."""
    a = np.asarray(values, dtype=float)
    return (
        float(np.median(a)),
        float(np.percentile(a, 25)),
        float(np.percentile(a, 75)),
    )


# --------------------------------------------------------------------------- #
# tab_build: per-phase timing breakdown (median [Q25, Q75])                   #
# --------------------------------------------------------------------------- #

def emit_tab_build() -> dict:
    data = json.loads(EXP6.read_text())
    rows = data["build_results"]

    fields = [
        ("LECT cache",      "lect_ms"),
        ("Grow",            "grow_ms"),
        ("Coarsen 1",       "coarsen1_ms"),
        ("Bridge repair",   "bridge_ms"),
        ("Coarsen 2",       "coarsen2_ms"),
        ("Adjacency",       "adjacency_ms"),
        ("\\quad pre-seed", "adjacency_pre_seed_ms"),
        ("\\quad seed-bridge", "seed_bridge_ms"),
        ("\\quad final",    "adjacency_final_ms"),
        ("Total",           "total_ms"),
    ]

    canonical = {}
    lines = []
    lines.append(r"% Auto-generated by cpp/v6/scripts/regen_paper_tables.py")
    lines.append(r"% Source: " + str(EXP6.relative_to(REPO)))
    lines.append(r"\begin{tabular}{lrrr}")
    lines.append(r"\toprule")
    lines.append(r"Phase & Median (ms) & Q25 (ms) & Q75 (ms) \\")
    lines.append(r"\midrule")
    for label, key in fields:
        vals = [r[key] for r in rows]
        m, q1, q3 = iqr(vals)
        canonical[f"build/{key}/median_ms"] = m
        canonical[f"build/{key}/q25_ms"] = q1
        canonical[f"build/{key}/q75_ms"] = q3
        lines.append(f"{label} & {m:.1f} & {q1:.1f} & {q3:.1f} \\\\")
    lines.append(r"\midrule")
    boxes = [r["boxes_final"] for r in rows]
    edges = [r["edges"] for r in rows]
    bm, bq1, bq3 = iqr(boxes)
    em, eq1, eq3 = iqr(edges)
    canonical["build/boxes_final/median"] = bm
    canonical["build/boxes_final/q25"] = bq1
    canonical["build/boxes_final/q75"] = bq3
    canonical["build/edges/median"] = em
    canonical["build/edges/q25"] = eq1
    canonical["build/edges/q75"] = eq3
    lines.append(f"Boxes (final) & {bm:.0f} & {bq1:.0f} & {bq3:.0f} \\\\")
    lines.append(f"Edges & {em:.0f} & {eq1:.0f} & {eq3:.0f} \\\\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    (GEN / "tab_build.tex").write_text("\n".join(lines) + "\n")
    return canonical


# --------------------------------------------------------------------------- #
# tab_ablation: median build/query/length per config (with IQR for build/query)
# --------------------------------------------------------------------------- #

def emit_tab_ablation() -> dict:
    data = json.loads(EXP5.read_text())
    rows = data["results"]

    canonical = {}
    lines = []
    lines.append(r"% Auto-generated by cpp/v6/scripts/regen_paper_tables.py")
    lines.append(r"% Source: " + str(EXP5.relative_to(REPO)))
    lines.append(r"\begin{tabular}{lrrrrrr}")
    lines.append(r"\toprule")
    lines.append(r"Config & Build med (s) & Build IQR (s) & Boxes & Query med (s) & Query IQR (s) & Len (rad) \\")
    lines.append(r"\midrule")
    for r in rows:
        bm, bq1, bq3 = r["build_median"], r["build_q25"], r["build_q75"]
        qm, qq1, qq3 = r["query_median"], r["query_q25"], r["query_q75"]
        bx = r["boxes"]
        ln = r["len_median"]
        nm = r["name"]
        key = nm.replace(" ", "_").replace(":", "").replace("/", "_")
        canonical[f"abl/{key}/build_median_s"] = bm
        canonical[f"abl/{key}/build_q25_s"] = bq1
        canonical[f"abl/{key}/build_q75_s"] = bq3
        canonical[f"abl/{key}/query_median_s"] = qm
        canonical[f"abl/{key}/query_q25_s"] = qq1
        canonical[f"abl/{key}/query_q75_s"] = qq3
        canonical[f"abl/{key}/boxes"] = bx
        canonical[f"abl/{key}/len_median_rad"] = ln
        lines.append(
            f"{nm} & {bm:.2f} & [{bq1:.2f},\\,{bq3:.2f}] & {bx} "
            f"& {qm:.3f} & [{qq1:.3f},\\,{qq3:.3f}] & {ln:.3f} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    (GEN / "tab_ablation.tex").write_text("\n".join(lines) + "\n")
    return canonical


def write_canonical_csv(rows: dict) -> None:
    out = GEN / "canonical_numbers.csv"
    with out.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["key", "value"])
        for k in sorted(rows):
            v = rows[k]
            if isinstance(v, float):
                w.writerow([k, f"{v:.6g}"])
            else:
                w.writerow([k, v])


def main() -> None:
    canonical = {}
    canonical.update(emit_tab_build())
    canonical.update(emit_tab_ablation())
    write_canonical_csv(canonical)
    print(f"wrote {GEN/'tab_build.tex'}")
    print(f"wrote {GEN/'tab_ablation.tex'}")
    print(f"wrote {GEN/'canonical_numbers.csv'}")
    print(f"  build total median = {canonical['build/total_ms/median_ms']:.1f} ms"
          f"  IQR=[{canonical['build/total_ms/q25_ms']:.1f}, "
          f"{canonical['build/total_ms/q75_ms']:.1f}] ms")
    print(f"  abl Full BT build median = "
          f"{canonical['abl/Full/build_median_s']:.3f} s,"
          f" query median = {canonical['abl/Full/query_median_s']:.3f} s")


if __name__ == "__main__":
    main()
