#!/usr/bin/env python3
"""B2: Paired Wilcoxon signed-rank test on per-seed baseline data.

Pairs are (query, seed) tuples (n = 5 queries x 5 seeds = 25). We compare
RRT-Connect vs PRM on (i) query time and (ii) path length, using the
per-seed entries in phase4_baselines_seeds5_20260422_1801.json.

SBF is deterministic per scene fingerprint (cache hit -> identical envelope
and corridor across seeds), so its values are reported as single points
in the baseline tables and excluded from the seed-paired test here.
"""
from __future__ import annotations
import json, sys
from pathlib import Path
from scipy.stats import wilcoxon

ROOT = Path(__file__).resolve().parents[1]
SRC  = ROOT / "experiments/results_new/phase4_baselines_seeds5_20260422_1801.json"
OUT  = ROOT / "doc/generated/tab_wilcoxon.tex"

QUERIES = ["AS->TS", "TS->CS", "CS->LB", "LB->RB", "RB->AS"]


def collect(method: dict, key: str):
    """Return list of (query, seed_idx, value or None) entries."""
    out = []
    for q in QUERIES:
        for i, rec in enumerate(method.get(q, [])):
            v = rec.get(key)
            if rec.get("success") and v is not None:
                out.append((q, i, float(v)))
            else:
                out.append((q, i, None))
    return out


def paired(a, b):
    xs, ys = [], []
    for (qa, ia, va), (qb, ib, vb) in zip(a, b):
        assert (qa, ia) == (qb, ib)
        if va is not None and vb is not None:
            xs.append(va); ys.append(vb)
    return xs, ys


def main():
    d = json.loads(SRC.read_text())
    rrt = d["rrt_connect"]; prm = d["prm"]

    rows = []
    for metric, key in [("query time (s)", "time_s"),
                        ("path length (rad)", "path_length")]:
        a = collect(rrt, key); b = collect(prm, key)
        xs, ys = paired(a, b)
        n = len(xs)
        try:
            res = wilcoxon(xs, ys, zero_method="wilcox", alternative="two-sided")
            W = res.statistic; p = res.pvalue
        except ValueError as e:
            W, p = float("nan"), float("nan")
            print(f"[warn] {metric}: {e}", file=sys.stderr)
        med_r = sorted(xs)[n//2]
        med_p = sorted(ys)[n//2]
        sig = "$\\star$" if p < 0.05 else ""
        rows.append((metric, n, med_r, med_p, W, p, sig))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT_ZH = OUT.with_name("tab_wilcoxon_zh.tex")

    def emit(path, lang):
        if lang == "en":
            cap = ("Paired Wilcoxon signed-rank test of RRT-Connect vs.\\ PRM on the "
                   "Marcucci scene, pairing by (query, seed) with up to "
                   "$5\\times 5=25$ samples per metric (PRM failures dropped). "
                   "SBF is deterministic per scene fingerprint and reported as a "
                   "single point in \\Cref{tab:baselines_v2}.")
            head = "Metric & $n$ & RRT med. & PRM med. & $W$ & $p$ & sig."
        else:
            cap = ("RRT-Connect 与 PRM 的成对 Wilcoxon 符号秩检验（Marcucci 场景，"
                   "按 (查询, 种子) 配对，至多 $5\\times 5=25$ 对，PRM 失败样本被剔除）。"
                   "SBF 在固定场景指纹下确定性运行，因此在 \\Cref{tab:baselines_v2} "
                   "中以单点形式报告。")
            head = "指标 & $n$ & RRT 中位 & PRM 中位 & $W$ & $p$ & 显著"
        with path.open("w") as f:
            f.write("% Auto-generated by scripts/wilcoxon_baselines.py -- do not edit by hand.\n")
            f.write("\\begin{table}[t]\n\\centering\n")
            f.write(f"\\caption{{{cap}}}\n")
            f.write("\\label{tab:wilcoxon}\n")
            f.write("\\begin{tabular}{lcccccc}\n\\toprule\n")
            f.write(head + "\\\\\n\\midrule\n")
            for metric, n, mr, mp, W, p, sig in rows:
                m_disp = metric
                if lang == "zh":
                    m_disp = {"query time (s)": "查询时间 (s)",
                              "path length (rad)": "路径长度 (rad)"}.get(metric, metric)
                f.write(f"{m_disp} & {n} & {mr:.4g} & {mp:.4g} & {W:.1f} & {p:.3g} & {sig}\\\\\n")
            f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

    emit(OUT, "en")
    emit(OUT_ZH, "zh")
    print(f"wrote {OUT} and {OUT_ZH}")
    for r in rows:
        print(r)


if __name__ == "__main__":
    main()
