// ═══════════════════════════════════════════════════════════════════════════
// SafeBoxForest v2 — GCPC (Global Critical Point Cache)
// ═══════════════════════════════════════════════════════════════════════════
//
// Precomputed critical points of FK position for each active link, stored
// in a KD-tree for fast orthogonal range queries.
//
// Symmetry reductions applied:
//   - q₀ fully eliminated (atan2 reconstruction at query time)
//   - q₁ period-π: only q₁ ∈ [0,π] stored; reflected at query time
//   - q₆ conditionally skipped (when d₆=0, a₆=0, no tool)
//
// Binary cache format: GCPC (see GcpcCache::save / load)
//
#pragma once

#include "sbf/robot/robot.h"
#include "sbf/common/types.h"
#include <Eigen/Core>
#include <vector>
#include <string>
#include <cstdint>
#include <cstring>
#include <memory>

namespace sbf {
namespace envelope {

// ═══════════════════════════════════════════════════════════════════════════
//  CriticalPoint — one cached interior critical point
// ═══════════════════════════════════════════════════════════════════════════
struct GcpcPoint {
    // Joint configuration: q₁..qₖ (q₁ ∈ [0,π], others ∈ [-π,π])
    // q₀ is NOT stored — analytically reconstructed at query time.
    double q_eff[7];       // max 7 joints; only first n_eff used
    int    n_eff;          // number of effective joints

    int    link_id;        // 0-based frame index (e.g., 2, 4, 6, 7)
    int    direction;      // 0 = xy (radial R²), 1 = z

    // Precomputed FK sub-chain values (in post-T₀ frame)
    double A;              // p_local_x (for xy: used in R = √(A²+B²))
    double B;              // p_local_y (for xy: used in R)
    double C;              // p_local_z (for z direction)
    double R;              // √(A²+B²) — radial distance (precomputed)
};

// ═══════════════════════════════════════════════════════════════════════════
//  KD-Tree node — for range queries over joint-space coordinates
// ═══════════════════════════════════════════════════════════════════════════
struct KdNode {
    int      split_dim;    // dimension to split on (round-robin)
    double   split_val;    // median value in split dimension
    int      left;         // left child index (-1 = leaf)
    int      right;        // right child index (-1 = leaf)
    int      point_idx;    // if leaf: index into points array; else -1
};

// ═══════════════════════════════════════════════════════════════════════════
//  Per-link cache section
// ═══════════════════════════════════════════════════════════════════════════
struct GcpcLinkSection {
    int link_id;           // 0-based frame index
    int n_eff_joints;      // effective DOF for this link (after q₀ elimination)
    int n_points;          // number of critical points for this link
    bool q6_skipped;       // whether q₆ was skipped for this link

    std::vector<GcpcPoint> points;
    std::vector<KdNode>    kd_tree;
    int                    kd_root;  // root node index in kd_tree
};

// ═══════════════════════════════════════════════════════════════════════════
//  Query result — a critical point matched in an interval query
// ═══════════════════════════════════════════════════════════════════════════
struct GcpcQueryResult {
    const GcpcPoint* point;    // pointer to cached point
    double q0_optimal;         // reconstructed q₀
    bool   q1_reflected;       // whether q₁ was reflected (q₁ - π)
    double q1_actual;          // actual q₁ used (after reflection if any)
};

// ═══════════════════════════════════════════════════════════════════════════
//  Query statistics (forward-declared before GcpcCache)
// ═══════════════════════════════════════════════════════════════════════════
struct GcpcQueryStats {
    int n_cache_matches = 0;     // points found in cache
    int n_q1_reflected = 0;      // points from q₁ reflection
    int n_q0_valid = 0;          // points with q₀ in range
    int n_boundary_kpi2 = 0;     // Phase B: kπ/2 boundary points
    int n_boundary_atan2 = 0;    // Phase C: 1D atan2 points
    int n_fk_calls = 0;          // total FK evaluations

    // IFK pruning stats (Phase C face-level bound pruning)
    int n_ifk_prune_checks = 0;  // faces checked via incremental IFK
    int n_ifk_pruned = 0;        // faces pruned (skipped bg enumeration)
    int n_ifk_not_pruned = 0;    // faces that survived pruning
};

// ═══════════════════════════════════════════════════════════════════════════
//  GcpcCache — Main cache class
// ═══════════════════════════════════════════════════════════════════════════
class GcpcCache {
public:
    GcpcCache() = default;

    // ── Construction ─────────────────────────────────────────────────────

    /// Load from JSON file (generated by precompute_gcpc.jl).
    /// Builds KD-trees for each link section.
    bool load_json(const std::string& path, const Robot& robot);

    /// Load from binary GCPC cache file.
    bool load(const std::string& path);

    /// Save to binary GCPC cache file.
    bool save(const std::string& path) const;

    /// Build cache from a Robot + set of critical points.
    /// Points should be in the q₁∈[0,π] half-range.
    void build(const Robot& robot,
               const std::vector<GcpcPoint>& points);

    // ── Query ────────────────────────────────────────────────────────────

    /// Find all critical points for the given link within the joint interval.
    /// intervals: full 7-DOF joint intervals [lo, hi] for each joint.
    /// Returns matched points with q₀ reconstructed and q₁ reflected as needed.
    void query_link(int link_id,
                    const Interval* intervals,
                    std::vector<GcpcQueryResult>& results) const;

    /// Evaluate cached + boundary critical points and compute tight AABB.
    /// This is the main entry point for the GCPC query pipeline.
    ///   Phase A: Cache lookup (KD-tree range query + reconstruction)
    ///   Phase B: Boundary kπ/2 enumeration
    ///   Phase C: Boundary 1D atan2
    /// out_aabb: [n_active * n_sub * 6] floats
    void derive_aabb_with_gcpc(
        const Robot& robot,
        const std::vector<Interval>& intervals,
        int n_sub,
        float* out_aabb,
        GcpcQueryStats* out_stats = nullptr) const;

    // ── Accessors ────────────────────────────────────────────────────────

    bool is_loaded() const { return !sections_.empty(); }
    int  n_links()   const { return static_cast<int>(sections_.size()); }
    int  n_total_points() const;

    const GcpcLinkSection* find_section(int link_id) const;

    /// Robot's base d₀ (needed for z reconstruction)
    double d0() const { return d0_; }

private:
    // ── KD-tree construction ─────────────────────────────────────────────
    void build_kdtree(GcpcLinkSection& section);

    int  build_kdtree_recursive(
        GcpcLinkSection& section,
        std::vector<int>& indices,
        int lo, int hi, int depth);

    // ── KD-tree range query ──────────────────────────────────────────────
    void kdtree_range_query(
        const GcpcLinkSection& section,
        int node_idx,
        const double* lo, const double* hi,
        int depth,
        std::vector<int>& matched_indices) const;

    // ── q₀ reconstruction ────────────────────────────────────────────────
    // For xy direction: q₀* = atan2(-B, A)
    // Then p_x = R·cos(q₀-q₀*), p_y = R·sin(q₀-q₀*)
    // max p_x over q₀ ∈ [lo₀, hi₀] = R if q₀* ∈ [lo₀, hi₀], else max(R·cos(lo₀-q₀*), R·cos(hi₀-q₀*))
    // For z direction: p_z = C + d₀, independent of q₀ → always valid if interval non-empty
    static double reconstruct_q0_xy(double A, double B);
    static bool   q0_in_range(double q0, double lo0, double hi0);

    // ── Data ─────────────────────────────────────────────────────────────
    std::string robot_name_;
    double d0_ = 0.0;                        // base d₀ offset
    bool   has_tool_ = false;
    std::vector<GcpcLinkSection> sections_;   // one per active link
};

} // namespace envelope
} // namespace sbf
