#!/usr/bin/env python3
"""Generate paper-ready LaTeX tables from experiment JSON data.

Reads s1/s2/s3 results and writes tab1–tab3 .tex files.
Run from v5/:
    python python/scripts/gen_paper_tables.py
"""
import json
import os
import sys
from collections import defaultdict

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "experiments", "results")
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "paper", "generated")


def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def write_tex(tex, path):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(tex)
    print(f"  Wrote {path}")


# ── Helpers ──────────────────────────────────────────────────

EP_ORDER = ["IFK", "CritSample", "Analytical", "GCPC"]
ENV_ORDER = ["LinkIAABB", "LinkIAABB_Grid", "Hull16_Grid"]

def esc(s):
    return s.replace("_", r"\_")


# ── Table 1: Envelope Volume ────────────────────────────────

def gen_tab1(s1_data):
    rows = s1_data["rows"]
    # Separate by robot
    r2 = [r for r in rows if r["robot"] == "2dof"]
    r7 = [r for r in rows if r["robot"] == "panda"]

    # Build lookup: (ep, env) -> row
    lut2 = {(r["endpoint"], r["envelope"]): r for r in r2}
    lut7 = {(r["endpoint"], r["envelope"]): r for r in r7}

    # IFK-LinkIAABB as baseline for ratio
    base2 = lut2.get(("IFK", "LinkIAABB"), {}).get("volume_mean", 1.0)
    base7 = lut7.get(("IFK", "LinkIAABB"), {}).get("volume_mean", 1.0)

    # Find best volume for 7-DOF
    vols7 = [lut7[(ep, env)]["volume_mean"]
             for ep in EP_ORDER for env in ENV_ORDER
             if (ep, env) in lut7]
    best7 = min(vols7) if vols7 else 0

    lines = [
        r"% Auto-generated by gen_paper_tables.py",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Envelope volume across pipeline configurations",
        r"  (500 random boxes, width $w{=}0.2$\,rad).",
        r"  $V$ = mean volume;",
        r"  Ratio = $V / V_{\text{IFK-LinkIAABB}}$.}",
        r"\label{tab:envelope_volume}",
        r"\setlength{\tabcolsep}{4pt}",
        r"\small",
        r"\begin{tabular}{@{}ll cc cc c@{}}",
        r"\toprule",
        r" & & \multicolumn{2}{c}{2-DOF} & \multicolumn{2}{c}{7-DOF (Panda)} & \\",
        r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}",
        r"Source & Envelope & $V$ & Ratio & $V$ & Ratio & Cert.\ \\",
        r"\midrule",
    ]

    prev_ep = None
    for ep in EP_ORDER:
        for env in ENV_ORDER:
            key = (ep, env)
            d2 = lut2.get(key, {})
            d7 = lut7.get(key, {})
            v2 = d2.get("volume_mean", 0)
            v7 = d7.get("volume_mean", 0)
            safe = d7.get("safe", d2.get("safe", False))

            ratio2 = v2 / base2 * 100 if base2 > 0 else 0
            ratio7 = v7 / base7 * 100 if base7 > 0 else 0

            # Bold best 7-DOF
            v7_str = f"{v7:.3f}"
            if abs(v7 - best7) < 1e-6:
                v7_str = r"\textbf{" + v7_str + "}"

            ep_str = ep if ep != prev_ep else ""
            prev_ep = ep

            safe_str = r"\checkmark" if safe else ""

            lines.append(
                f"  {ep_str} & {esc(env)} "
                f"& {v2:.4f} & {ratio2:.1f}\\% "
                f"& {v7_str} & {ratio7:.1f}\\% "
                f"& {safe_str} \\\\"
            )
        if ep != EP_ORDER[-1]:
            lines.append(r"  \addlinespace")

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    return "\n".join(lines)


# ── Table 2: Computation Timing ─────────────────────────────

def gen_tab2(s2_data):
    rows = s2_data["rows"]
    r2 = [r for r in rows if r["robot"] == "2dof"]
    r7 = [r for r in rows if r["robot"] == "panda"]

    lut2 = {(r["endpoint"], r["envelope"]): r for r in r2}
    lut7 = {(r["endpoint"], r["envelope"]): r for r in r7}

    lines = [
        r"% Auto-generated by gen_paper_tables.py",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Per-box computation time ($\mu$s) on 7-DOF Panda",
        r"  (50\,k samples).",
        r"  EP = endpoint-iAABB source; Env = envelope rasterisation;",
        r"  Speedup = Analytical-LinkIAABB / Total.}",
        r"\label{tab:timing}",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\small",
        r"\begin{tabular}{@{}ll rrr r@{}}",
        r"\toprule",
        r"Source & Envelope & EP\,($\mu$s) & Env\,($\mu$s)"
        r" & Total\,($\mu$s) & Speedup \\",
        r"\midrule",
    ]

    # Analytical-LinkIAABB as baseline
    base = lut7.get(("Analytical", "LinkIAABB"), {}).get("total_us_mean", 1.0)

    # Find best total for bold
    totals7 = [lut7[(ep, env)]["total_us_mean"]
               for ep in EP_ORDER for env in ENV_ORDER
               if (ep, env) in lut7]
    best = min(totals7) if totals7 else 0

    prev_ep = None
    for ep in EP_ORDER:
        for env in ENV_ORDER:
            d = lut7.get((ep, env), {})
            ep_us = d.get("ep_us_mean", 0)
            env_us = d.get("env_us_mean", 0)
            total = d.get("total_us_mean", 0)
            speedup = base / total if total > 0 else 0

            # Format
            def fnum(v):
                if v < 0.1:
                    return f"{v:.2f}"
                elif v < 10:
                    return f"{v:.1f}"
                elif v < 1000:
                    return f"{v:.0f}"
                else:
                    return f"{v:,.0f}"

            total_str = fnum(total)
            if abs(total - best) < 0.01:
                total_str = r"\textbf{" + total_str + "}"

            ep_str = ep if ep != prev_ep else ""
            prev_ep = ep

            spd_str = f"{speedup:,.0f}$\\times$" if speedup >= 10 else f"{speedup:.1f}$\\times$"

            lines.append(
                f"  {ep_str} & {esc(env)} "
                f"& {fnum(ep_us)} & {fnum(env_us)} "
                f"& {total_str} & {spd_str} \\\\"
            )
        if ep != EP_ORDER[-1]:
            lines.append(r"  \addlinespace")

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    return "\n".join(lines)


# ── Table 3: End-to-End Planning ────────────────────────────

def gen_tab3(s3_data):
    trials = s3_data.get("trials", [])
    if not trials:
        return "% No e2e data available.\n"

    # Group by (planner, scene)
    groups = defaultdict(list)
    for t in trials:
        groups[(t["planner"], t["scene"])].append(t)

    # Ordered scene list
    SCENE_ORDER = [
        "2dof_simple", "2dof_narrow", "2dof_cluttered",
        "panda_tabletop", "panda_shelf", "panda_multi_obstacle",
    ]
    scene_short = {
        "2dof_simple": "2D-S",
        "2dof_narrow": "2D-N",
        "2dof_cluttered": "2D-C",
        "panda_tabletop": "P-Tab",
        "panda_shelf": "P-Shf",
        "panda_multi_obstacle": "P-Multi",
    }
    all_planners = {t["planner"] for t in trials}

    # Filter to scenes that have at least one planner with >= 5 trials
    scenes_with_data = [s for s in SCENE_ORDER if any(
        (p, s) in groups and len(groups[(p, s)]) >= 5 for p in all_planners)]

    n_sc = len(scenes_with_data)
    if n_sc == 0:
        return "% No complete e2e scene data.\n"

    col_spec = "@{}ll" + "c" * n_sc + "@{}"
    scene_hdrs = " & ".join(scene_short.get(s, esc(s)) for s in scenes_with_data)

    lines = [
        r"% Auto-generated by gen_paper_tables.py",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{End-to-end planning: success rate (\%) / mean time (ms)",
        r"  across 12 SBF configurations and benchmark scenes",
        r"  (30 seeded trials each).}",
        r"\label{tab:e2e}",
        r"\setlength{\tabcolsep}{3pt}",
        r"\small",
        r"\begin{tabular}{" + col_spec + "}",
        r"\toprule",
        r"Source & Envelope & " + scene_hdrs + r" \\",
        r"\midrule",
    ]

    import numpy as np
    prev_ep = None
    for ep in EP_ORDER:
        for env in ENV_ORDER:
            planner = f"SBF-{ep}-{env}"
            if planner not in all_planners:
                continue

            cells = []
            for scene in scenes_with_data:
                trs = groups.get((planner, scene), [])
                if not trs or len(trs) < 5:
                    cells.append("---")
                    continue
                n = len(trs)
                n_ok = sum(1 for t in trs
                           if t.get("result", {}).get("success", False))
                succ = 100.0 * n_ok / n
                times = [t["result"]["planning_time_s"] * 1000
                         for t in trs
                         if t.get("result", {}).get("success", False)
                         and "planning_time_s" in t.get("result", {})]
                if times:
                    mean_ms = np.mean(times)
                    if mean_ms < 100:
                        time_str = f"{mean_ms:.1f}"
                    elif mean_ms < 10000:
                        time_str = f"{mean_ms:,.0f}"
                    else:
                        time_str = f"{mean_ms / 1000:.1f}s"
                else:
                    time_str = "---"
                cells.append(f"{succ:.0f}/{time_str}")

            ep_str = ep if ep != prev_ep else ""
            prev_ep = ep
            cell_str = " & ".join(cells)
            lines.append(f"  {ep_str} & {esc(env)} & {cell_str} \\\\")
        if ep != EP_ORDER[-1]:
            lines.append(r"  \addlinespace")

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
    ]
    return "\n".join(lines)


# ── Table 4: Baseline Comparison ────────────────────────────

def gen_tab4(s4_data):
    """Baseline comparison table from ExperimentResults JSON."""
    trials = s4_data.get("trials", [])
    if not trials:
        return "% No baseline data available.\n"

    import numpy as np

    # Group by (planner, scene)
    groups = defaultdict(list)
    planners_set = set()
    scenes_set = set()
    for t in trials:
        groups[(t["planner"], t["scene"])].append(t)
        planners_set.add(t["planner"])
        scenes_set.add(t["scene"])

    SCENE_ORDER = [
        "2dof_simple", "2dof_narrow", "2dof_cluttered",
        "panda_tabletop", "panda_shelf", "panda_multi_obstacle",
    ]
    scenes = [s for s in SCENE_ORDER if s in scenes_set]

    # Aggregate per planner across all scenes
    planner_stats = {}
    for p in sorted(planners_set):
        all_success = []
        all_times = []
        all_lengths = []
        for s in scenes:
            trs = groups.get((p, s), [])
            for t in trs:
                ok = t.get("result", {}).get("success", False)
                all_success.append(ok)
                if ok:
                    all_times.append(t["result"].get("planning_time_s", 0) * 1000)
                    all_lengths.append(t.get("metrics", {}).get("path_length", 0))
        n = len(all_success)
        n_ok = sum(all_success)
        succ = 100.0 * n_ok / n if n > 0 else 0
        mean_t = np.mean(all_times) if all_times else float("nan")
        std_t = np.std(all_times) if all_times else float("nan")
        mean_l = np.mean(all_lengths) if all_lengths else float("nan")
        planner_stats[p] = (succ, mean_t, std_t, mean_l)

    lines = [
        r"% Auto-generated by gen_paper_tables.py",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Baseline comparison across benchmark scenes"
        r" (30 trials, mean~$\pm$~std).}",
        r"\label{tab:baselines}",
        r"\small",
        r"\begin{tabular}{@{}lccc@{}}",
        r"\toprule",
        r"Planner & Success\,(\%) & Time\,(ms) & Path Length \\",
        r"\midrule",
    ]

    # SBF planners first, then OMPL
    sbf = sorted(p for p in planners_set if p.startswith("SBF"))
    ompl = sorted(p for p in planners_set if not p.startswith("SBF"))

    for group_name, group_planners in [("SBF", sbf), ("Baselines", ompl)]:
        if not group_planners:
            continue
        for p in group_planners:
            succ, mt, st, ml = planner_stats[p]
            name = esc(p)
            if np.isnan(mt):
                time_str = "---"
                len_str = "---"
            else:
                time_str = f"{mt:.1f}$\\pm${st:.1f}" if mt < 10000 else f"{mt/1000:.1f}s"
                len_str = f"{ml:.2f}"
            lines.append(f"  {name} & {succ:.0f} & {time_str} & {len_str} \\\\")
        if group_name == "SBF" and ompl:
            lines.append(r"  \midrule")

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    return "\n".join(lines)


# ── Table 6: Link-iAABB Subdivision Tightness ───────────────

def gen_tab_subdivision(bench_path):
    """Parse bench_link_envelope results to show subdivision improvement."""
    if not os.path.exists(bench_path):
        return None

    with open(bench_path, "r", encoding="utf-8") as f:
        text = f.read()

    import re

    # Parse blocks: width = X.XX rad
    width_blocks = re.split(r"width\s*=\s*(\d+\.\d+)\s*rad", text)
    if len(width_blocks) < 3:
        return None

    # Collect data: list of (width, interval_idx, config, gridvol)
    records = []
    for i in range(1, len(width_blocks), 2):
        width = float(width_blocks[i])
        block = width_blocks[i + 1]
        # Split by interval #N
        intervals = re.split(r"interval\s*#(\d+)", block)
        for j in range(1, len(intervals), 2):
            iv_idx = int(intervals[j])
            iv_text = intervals[j + 1]
            # Parse AABB(sub=N) rows
            for m in re.finditer(
                r"AABB\(sub=(\d+)\)\s+cold\s+[\d.]+\s+([\d.]+)\s+(\d+)\s+([\d.]+)",
                iv_text
            ):
                sub = int(m.group(1))
                gridvol = float(m.group(4))
                records.append((width, iv_idx, sub, gridvol))

    if not records:
        return None

    # Average GridVol across intervals for each (width, sub)
    from collections import defaultdict
    acc = defaultdict(list)
    for w, iv, sub, gv in records:
        acc[(w, sub)].append(gv)

    widths = sorted({w for w, _ in acc})
    subs = sorted({s for _, s in acc})

    # Build table
    lines = [
        r"% Auto-generated by gen_paper_tables.py",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Link-iAABB subdivision: union volume (m$^3$) decreases",
        r"  monotonically with subdivision count $N_{\text{sub}}$.",
        r"  IIWA14, CritSample source, 3 random intervals averaged.}",
        r"\label{tab:subdivision}",
        r"\small",
    ]

    n_w = len(widths)
    col_spec = "@{}r" + "r" * n_w + "@{}"
    w_hdrs = " & ".join(f"$w{{=}}{w:.2f}$" for w in widths)

    lines += [
        r"\begin{tabular}{" + col_spec + "}",
        r"\toprule",
        r"$N_{\text{sub}}$ & " + w_hdrs + r" \\",
        r"\midrule",
    ]

    for sub in subs:
        cells = []
        for w in widths:
            vals = acc.get((w, sub), [])
            if vals:
                import numpy as np
                mean_v = np.mean(vals)
                cells.append(f"{mean_v:.4f}")
            else:
                cells.append("---")
        lines.append(f"  {sub} & " + " & ".join(cells) + r" \\")

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    return "\n".join(lines)


# ── Main ────────────────────────────────────────────────────

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"Data dir: {DATA_DIR}")
    print(f"Output dir: {OUT_DIR}")

    # Tab 1
    s1_path = os.path.join(DATA_DIR, "s1_envelope_tightness", "results.json")
    if os.path.exists(s1_path):
        s1 = load_json(s1_path)
        write_tex(gen_tab1(s1), os.path.join(OUT_DIR, "tab1_envelope_volume.tex"))
    else:
        print(f"  SKIP tab1: {s1_path} not found")

    # Tab 2
    s2_path = os.path.join(DATA_DIR, "s2_envelope_timing", "results.json")
    if os.path.exists(s2_path):
        s2 = load_json(s2_path)
        write_tex(gen_tab2(s2), os.path.join(OUT_DIR, "tab2_computation_timing.tex"))
    else:
        print(f"  SKIP tab2: {s2_path} not found")

    # Tab 3
    s3_path = os.path.join(DATA_DIR, "s3_e2e", "results.json")
    if os.path.exists(s3_path):
        s3 = load_json(s3_path)
        write_tex(gen_tab3(s3), os.path.join(OUT_DIR, "tab3_e2e_planning.tex"))
    else:
        print(f"  SKIP tab3: {s3_path} not found")

    # Tab 4
    s4_path = os.path.join(DATA_DIR, "s4_baselines", "results.json")
    if os.path.exists(s4_path):
        s4 = load_json(s4_path)
        write_tex(gen_tab4(s4), os.path.join(OUT_DIR, "tab4_baselines.tex"))
    else:
        print(f"  SKIP tab4: {s4_path} not found")

    # Tab subdivision (from bench_link_envelope)
    bench_path = os.path.join(DATA_DIR, "..", "..", "bench_link_envelope_final.txt")
    if not os.path.exists(bench_path):
        bench_path = os.path.join(DATA_DIR, "..", "..",
                                  "bench_link_envelope_v3_utf8.txt")
    tex_sub = gen_tab_subdivision(bench_path)
    if tex_sub:
        write_tex(tex_sub, os.path.join(OUT_DIR, "tab7_subdivision.tex"))
    else:
        print("  SKIP tab6: no bench_link_envelope data")

    print("Done.")


if __name__ == "__main__":
    main()
